config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
    root to: "home#index"



    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do
        devise_for :users, controllers: {
          sessions: 'api/v1/users/sessions',
          registrations: 'api/v1/users/registrations'
        },path: '', path_names: {
          sign_in: 'login',
          sign_out: 'logout',
          registration: 'signup'
        }
        resources :users do 
          put "/otp_varify", to: "users#otp_varify", on: :collection
          put "/otp_varify_email", to: "users#otp_varify_email", on: :collection
        end
      end
    end

    namespace :api, constraints: { format: :json }  do
      namespace :v1, constraints: { format: :json }  do 
        resources :home do 
          get "/add_to_cart", to: "home#add_to_cart"  #post
          post "/like", to: "home#like"
        end
      end
    end

    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do 
        resources :products do 
          resources :comments
          collection do 
            get :options_for_variant
          end
          post "/like", to: "products#like"
        end
        resources :carts do 
          post "/update_cart", to: "carts#update_cart"
          delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
        end
        resources :orders do 
          post "/place_order", to: "orders#place_order", on: :collection
          get "/show_order_item", to: "orders#show_order_item", on: :member
          get "/pay", to: "orders#pay", on: :member
          post "/payments", to: "orders#payments", on: :collection
          patch "/cancel_order", to: "orders#cancel_order", on: :member
        end
        resources :addresses

        resources :variants
      end
    end
    
    get '/member-data', to: 'members#show'

    resources :home do 
      get "/add_to_cart", to: "home#add_to_cart"  #post
      post "/like", to: "home#like"
    end

    resources :carts do 
      post "/update_cart", to: "carts#update_cart"
      delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
    end

    post 'admin/products/change_variant_attribute' 

    resources :products do 
      resources :comments
      collection do 
        get :options_for_variant
      end
      post "/like", to: "products#like"
    end

    resources :variants

    resources :orders do 
      post "/place_order", to: "orders#place_order", on: :collection
      get "/show_order_item", to: "orders#show_order_item", on: :member
      get "/pay", to: "orders#pay", on: :member
      post "/payments", to: "orders#payments", on: :collection
      patch "/cancel_order", to: "orders#cancel_order", on: :member
      
    end

    resources :addresses

    resources :wishlists

end

app/controllers/api/v1/home_controller.rb
module Api 
    module V1
            class HomeController < ApiController
                before_action :authenticate_user!
                def index
                    # byebug
                    if current_user.user_type == "merchant"
                        @products = current_user.products
                        render json: @products
                    else
                        @products = Product.all
                        render json: @products
                    end
                end


                def like  
                    if current_user != 'merchant'
                        product = Product.find_by(id: params[:home_id])
                        # byebug
                        if current_user.likes.where(likeable_id: params[:home_id], likeable_type: "Product").present?
                            like = product.likes.find_by(likeable_id: params[:home_id])
                            like.destroy
                            render json: {meta: {message: 'Product deleted from wishlist...'}}
                        else
                            like = product.likes.new(user_id: current_user.id)
                            if like.save
                                render json: {meta: {message: 'Product added to wishlist...'}}
                            end        
                        end
                    else
                        render json: {message: 'not authorised'}
                    end
                end


                def show
                    @wishlist = Like.find_by(params[:id])
                    @product = Product.find(params[:id])
                    @pv = @product.product_variants
                    @comment = current_user.comments.find_by(product_id: params[:product_id])
                    render json: @product
                end
                    

                def add_to_cart
                    if current_user.user_type != "merchant"
                        cart = Cart.find_or_create_by(user_id: current_user.id)
                        if cart.present?
                           product = Product.find_by(id: params[:home_id])
                           if product != nil

                                if cart.cart_items.find_by(product_id: product.id).present?
                                    return render json: {meta: {message: 'prodct is already in cart'}}
                                end
                               
                               cart_item = cart.cart_items.new(product_id: product.id, total_price: product.price, product_quantity: 1)

                                    if cart_item.save
                                        render json: {meta: {message: 'Product added to cart...'}}
                                    end
                            else
                                render json: {meta: {message: 'Product not found'}}
                            end
                        end
                    else
                        render json: {message: "you are not authorised"}
                    end
                end


            def product_params
                  # byebug
                  params.require(:product).permit(:category_id, :name, :price, :manufacturing_date, :image, 
                    product_variants_attributes: [:id, :variant_id, :variant_attribute_id, :_destroy])
            end

        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if current_user.user_type == "merchant"
            # @products = current_user.products
            @products = current_user.products.paginate(:page => params[:page], :per_page =>params[:per_page])
        else
            @products = Product.paginate(:page => params[:page], :per_page => params[:per_page])
        end
	end


    def like  
        product = Product.find_by(id: params[:home_id])
        # byebug
        if current_user.likes.where(likeable_id: params[:home_id], likeable_type: "Product").present?
            like = product.likes.find_by(likeable_id: params[:home_id])
            like.destroy
            flash[:wishlist] = "Product deleted from wishlist..."
            redirect_to home_index_path
        else
            like = product.likes.new(user_id: current_user.id)
            if like.save
                flash[:wishlist] = "Product added to wishlist..."
                redirect_to home_index_path
            end        
        end
    end


    def show
        @wishlist = Like.find_by(params[:id])
    	@product = Product.find(params[:id])
        @pv = @product.product_variants
        @comment = current_user.comments.find_by(product_id: params[:product_id])
    end
        

    def add_to_cart
    	cart = Cart.find_or_create_by(user_id: current_user.id)
        if cart.present?
    	   product = Product.find_by(id: params[:home_id])
           if cart.cart_items.find_by(product_id: product.id).present?
                flash[:message]="Product is already in cart" 
                redirect_to home_index_path
                return
            end
    	   cart_item = cart.cart_items.new(product_id: product.id, total_price: product.price, product_quantity: 1)

    	   if cart_item.save
                flash[:message] = "Product added to cart..."
    	   	    redirect_to home_index_path
    	   else
    	   	    flash[:alert] = "product not saved!!"  
    	   end

        end
    end


def product_params
      # byebug
      params.require(:product).permit(:category_id, :name, :price, :manufacturing_date, :image, 
        product_variants_attributes: [:id, :variant_id, :variant_attribute_id, :_destroy])
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
          <h4 align="right", padding="5px">  
              Logged in as <strong><%= current_user.email %></strong>
              <h4 align="right", margin="40px"><%= link_to 'Edit profile ', edit_user_registration_path, :class => 'navbar-link' %>  |
              <%= link_to "Logout ", destroy_user_session_path, method: :delete, :class => 'navbar-link'%> </h4>
          </h4>
<% else %>
          <h4>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>  |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          </h4>
<% end %>
<h3 class="mess"><%= flash[:message]%></h3>
<h3 class="mess"><%= flash[:wishlist]%></h3>

<h3 class="pp"><%= flash[:alert]%> </h3>
<center><h2>products</h2></center>


<div class="cards">
  <% @products.each do |hommme|%>

    <article class="card">
        <div class ="im">
        <% if hommme.image.present? %>
            <%= image_tag hommme.image, :size => "230x200" %> 
        <% end %>
        <h2 class="name"><%= hommme.name %></h2>
    
        <h3 class="price">$<%= hommme.price %></h3>
    
        <div class="button" id="but"><a href="<%= product_path(hommme.id) %>"><%= "more details"%></a>  </div><br><br>
        <%#= button_to "more details", home_path(hommme.id)%>
        
        <div class="button2">
            <% if current_user.user_type != "merchant"%>
                <%#byebug%>
                <%#if CartItem.find_by(product_id: params[:id]).cart.present?%>
                    <a href="<%= home_add_to_cart_path(hommme.id) %>"><%= "add to cart"%></a><br><br>

                <%#end%>
            <%end%>


            <% if current_user.user_type == "merchant"%>
                <%= link_to "Destroy", hommme, method: :delete, data: { confirm: "Are you sure?" } %>
            <%end%>
        </div>
        <%#byebug%>
            <% if current_user.likes.where(likeable_id: hommme.id, likeable_type: "Product").present?%>
                <%= link_to home_like_path(hommme.id), method: :post do%>
                    <h3 style="margin-left: 201px;"><%= image_tag "/assets/like.png", :size => "30x30" %></h3>
                <%end%>
            <%else%>
                <%= link_to home_like_path(hommme.id), method: :post do%>
                    <h3 style="margin-left: 201px;"><%= image_tag "/assets/like1.png", :size => "30x30" %></h3>
                <%end%>
            <%end%>
        </div>
    </article>
  <% end %>

</div>





    <div class=”row margin-twenty5-zero margin-b-zero pagination-row”>

    <div class=”col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero”>

    <ul class=”pagination”>

    <li class=”disabled”> <%= will_paginate @products %>


    </ul>

    </div>

    <div class=”col-lg-4 col-md-4 col-sm-5 col-xs-6 pagination-info”>

    <span class=”pull-right”><%= page_entries_info(@products) %></span>

    </div>

    </div>

    

app/views/home/show.html.erb
<h2>detail of product</h2>

<h3>Product name = <%= @product.name %> </h3>
<h3>Product price = <%= @product.price %> </h3>
<h3>Manufacturing Date of product = <%= @product.manufacturing_date %> </h3><br>
<%#byebug%>
<%if @product.product_variants.present?%>
    <h2>Variants of Product : </h2>
      <% @pv.each do |v|%>
          <%#= v.variant_id%>
          <h3><%= Variant.find_by(id: (v.variant_id)).name %> :
          <%= VariantAttribute.find_by(id: (v.variant_attribute_id)).name %></h3>
      <%end%>
<%end%>
<%if @product.image.present?%>
   <%= image_tag @product.image %></a>
<% end %>

<%= link_to "edit page", edit_product_path(@product)%>
 <a href="<%= home_add_to_cart_path(@product.id) %>"><%= "add to cart"%></a><br><br>

app/views/home/wishlist.html.erb
<h1>gsethfcy</h1>

<%#= @wishlist.id%>