config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
    root to: "home#index"



    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do
        devise_for :users, controllers: {
          sessions: 'api/v1/users/sessions',
          registrations: 'api/v1/users/registrations'
        },path: '', path_names: {
          sign_in: 'login',
          sign_out: 'logout',
          registration: 'signup'
        }
        resources :users do 
          put "/otp_varify", to: "users#otp_varify", on: :collection
          put "/otp_varify_email", to: "users#otp_varify_email", on: :collection
        end
      end
    end

    namespace :api, constraints: { format: :json }  do
      namespace :v1, constraints: { format: :json }  do 
        resources :home do 
          get "/add_to_cart", to: "home#add_to_cart"  #post
          post "/like", to: "home#like"
        end
      end
    end

    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do 
        resources :products do 
          resources :comments
          collection do 
            get :options_for_variant
          end
          post "/like", to: "products#like"
        end
        resources :carts do 
          post "/update_cart", to: "carts#update_cart"
          delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
        end
        resources :orders do 
          post "/place_order", to: "orders#place_order", on: :collection
          get "/show_order_item", to: "orders#show_order_item", on: :member
          get "/pay", to: "orders#pay", on: :member
          post "/payments", to: "orders#payments", on: :collection
          patch "/cancel_order", to: "orders#cancel_order", on: :member
        end
        resources :addresses

        resources :variants
      end
    end
    
    get '/member-data', to: 'members#show'

    resources :home do 
      get "/add_to_cart", to: "home#add_to_cart"  #post
      post "/like", to: "home#like"
    end

    resources :carts do 
      post "/update_cart", to: "carts#update_cart"
      delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
    end

    post 'admin/products/change_variant_attribute' 

    resources :products do 
      resources :comments
      collection do 
        get :options_for_variant
      end
      post "/like", to: "products#like"
    end

    resources :variants

    resources :orders do 
      post "/place_order", to: "orders#place_order", on: :collection
      get "/show_order_item", to: "orders#show_order_item", on: :member
      get "/pay", to: "orders#pay", on: :member
      post "/payments", to: "orders#payments", on: :collection
      patch "/cancel_order", to: "orders#cancel_order", on: :member
      
    end

    resources :addresses

    resources :wishlists

end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items, dependent: :destroy
	belongs_to :address

	enum status: [:created, :paymentcompleted, :cancelled, :refunded]

end

app/controllers/api/v1/orders_controller.rb
module Api
	module V1
		class OrdersController < ApiController
                before_action :authenticate_user!

			   respond_to :js, :json, :html
			   Razorpay.setup('rzp_test_sGKFWWIENwCHjV', 'EX65NY1GAg5e6mTzJGJmoBE6')

			   def index
			   		if current_user.user_type != "merchant"
				 		@order_items = current_user.order_items
				      	@orders = current_user.orders
				      	render json: @orders
			      		# render json: @order_items
			      	end
			   end

			   def show_order_item
			      # byebug
			      	@order_item = OrderItem.find(params[:id])
			      	@order_items = current_user.order_items.where.not(id: @order_item.id)
			      	@address = @order_item.order.address
			      	render json: @order_item
			   end


			   def place_order
			      if params[:address_id].present? 
			         cart = current_user.cart
			         if cart.present? and cart.cart_items.present? 
			            # byebug
			            price = cart.total_price * 100
			            @order = current_user.orders.new(total_price: price.to_i,total_quantity: cart.total_quantity, address_id: params[:address_id].to_i)
			      		# byebug 
			            cart.cart_items.each do |orderitem|
			              @order_item = @order.order_items.new(product_id: orderitem.product_id, total_price: orderitem.total_price, product_quantity: orderitem.product_quantity)
			            end

			            if @order.save
			               	cart.cart_items.delete_all 
			               	cart.update(total_price: 0, total_quantity: 0)
			            	# OrderMailer.order_confirmed(@order).deliver_now
			               	# cart.cart_items.destroy 
			               	order = Razorpay::Order.create(amount: price.to_i, currency: 'INR', receipt: 'TEST')
			               	# order = Razorpay::Order.create amount: price.to_i, currency: 'INR', receipt: 'TEST'
			               	@order.update(razorpay_order_id: order.id) #status created
			               	render json: {meta: {message: 'order placed'}}
			            end
			         else
			            render json: {meta:{message: 'nothing in cart'}}
			         
			         end
			      else
			         render json: {errors: 'please enter delivery address or create new!'}
			      end
			   end

		end
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   respond_to :js, :json, :html
	# def new 
 #    	@order = current_user.products.new
 #    end
   Razorpay.setup('rzp_test_sGKFWWIENwCHjV', 'EX65NY1GAg5e6mTzJGJmoBE6')

 	def index
      # byebug
 		@order_items = current_user.order_items
      @orders = current_user.orders
   end

   def show_order_item
      # byebug
      @order_item = OrderItem.find(params[:id])
      @order_items = current_user.order_items.where.not(id: @order_item.id)
      @address = @order_item.order.address
   end

   def update
      # byebug
      # @order_items = current_user.order_items
      @order = Order.find_by(id: params[:id])
      if @order.present?
         payment_response = {razorpay_order_id: params[:razorpay_order_id], razorpay_payment_id: params[:razorpay_payment_id], razorpay_signature: params[:razorpay_signature] }
         verify_result = Razorpay::Utility.verify_payment_signature(payment_response)
         if verify_result
            @order.update(razorpay_payment_id: params[:razorpay_payment_id], status: "paymentcompleted") #status payment_completed
            # byebug   
            OrderMailer.order_confirmed(@order, ).deliver_now
            redirect_to orders_path
         else
            flash[:error] = "something went wrong!!!"
            redirect_to orders_path
         end
      end
   end
   

   def cancel_order
      # byebug
      @order = Order.find_by_id(params[:id])
      # return redirect_to orders_path unless @order.present?
      if @order.status == "paymentcompleted" 
         refund = RefundPayment.new(@order).refund_payment
         @order.update(status: "refunded", razorpay_refund_id: refund.id)    #status canceled 
      elsif @order.status != "refunded" #or 
         @order.update(status: "cancelled")
      # byebug
      elsif @order.status == "created"
         @order.update(status: "cancelled")
      end
      redirect_to orders_path
   end

   def place_order
      # byebug 
      if params[:address_id].present? 
         cart = current_user.cart
         if cart.present? and cart.cart_items.present? 
            # byebug
            price = cart.total_price * 100
            @order = current_user.orders.new(total_price: price.to_i,total_quantity: cart.total_quantity, address_id: params[:address_id].to_i)
            cart.cart_items.each do |orderitem|
              @order_item = @order.order_items.new(product_id: orderitem.product_id, total_price: orderitem.total_price, product_quantity: orderitem.product_quantity)
            end

            if @order.save
               cart.cart_items.delete_all 
               cart.update(total_price: 0, total_quantity: 0)
               # cart.cart_items.destroy 
               order = Razorpay::Order.create(amount: price.to_i, currency: 'INR', receipt: 'TEST')
               # order = Razorpay::Order.create amount: price.to_i, currency: 'INR', receipt: 'TEST'
               @order.update(razorpay_order_id: order.id) #status created
               redirect_to pay_order_path(@order.id)
            end
         else
            redirect_to orders_path
         
         end
      else
         flash[:error] = "please select delivery address or create new!!" 
         redirect_to carts_path
      end
   end

   def pay
      # byebug
      @order = Order.find_by(id: params[:id])
      @cart = current_user.cart
   end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<style>
  #button {
  color: black;
  background-color: lightblue;
  border-radius: 50px;
  display: flex;
  justify-content: center;
  align-items: left;
  text-align: left;
  height: 2em;
  width: 7em;
  font-size: medium;
  font-weight: 60;
  //margin: 3px;
  text-decoration: none;
  padding: 5px;
}

</style>
<h2>all orders</h2>

<h3 align="right"><%= link_to 'back', home_index_path %></h3>

<% @order_items.each do |order_item| %>
  <div class="column">
    <%if order_item.product.image.present?%>
       <%= image_tag order_item.product.image, :size => "100x150" %>
    <%end%>
  </div>      
  
        <div class="column">
          <h4>price = <%= order_item.total_price%></h4>
          <h4> product id = <%= order_item.product_id%><br></h4>
          <h4>name = <%= order_item.product.name%></h4>
          <h4>product_quantity =<%= order_item.product_quantity%></h4>
          <h3>created_at =<%= order_item.created_at.strftime("%m-%d-%Y at %I:%M%p")%></h3>
          <h3><strong>status = <%= order_item.order.status%></strong></h3>
          <%#byebug%>
           
          <%= link_to "show details of order ", show_order_item_order_path(order_item.id)%>



       
          <% if order_item.order.status == "created" or order_item.order.status == "paymentcompleted" %>
              <h4 id="button"><%= link_to "cancel order", cancel_order_order_path(order_item.order_id),
                                                         method: :patch,data: { confirm: "Are you sure?" } %></h4>
          <%end%>
        </div><br>
<%end%>


  


    

app/views/orders/invoice.html.erb
<style>
  #button {
  color: black;
  background-color: lightblue;
  border-radius: 50px;
  display: flex;
  justify-content: center;
  align-items: left;
  text-align: left;
  height: 2em;
  width: 7em;
  font-size: medium;
  font-weight: 60;
  //margin: 3px;
  text-decoration: none;
  padding: 5px;
}

</style>
<center>	<h2>your order</h2>   

  
  

<br><br>

 <!-- @order.order_items.first.product.price -->

<table  style="width:60%">
      <tr>
        <th>Image </th>
        <th>price </th>
        <th>name </th>
        <th> product_quantity </th>
        <th> total_price </th>
      </tr>

      <tr>
        <% @order.order_items.each do |order_item| %>
        <td><%= image_tag order_item.product.image if order_item.product.image %></td>
        <td><%= order_item.product.price %></td>
        <td><%= order_item.product.name %></td>
        <td><%= order_item.product_quantity %></td>
        <td><%= order_item.total_price %><td>
      </tr>
			
        <%end%>
      
</table>
	    <%#byebug%>
	       
	 <hr>
	 	<div class="column">
		  	<h4>total price  = <%= @order.total_price/100%> &nbsp; &nbsp; &nbsp;
		  	total quantity = <%= @order.total_quantity%></h4>
		</div>
     
    
</center>

app/views/orders/pay.html.erb
<h3>pay for orders</h3>
<div >
    <button id="rzp-button1" >Pay</button>
</div>

<script>
  document.getElementById('rzp-button1').onclick = function(e){
    
  var options = {
    "key": "rzp_test_sGKFWWIENwCHjV", 
    "amount": "<%= @order.total_price %>", 
    "currency": "INR",
    "name": "Product App",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "<%= @order.razorpay_order_id %>",
    "handler": function (response){
        // alert(response.razorpay_payment_id);
        // alert(response.razorpay_order_id);
        // alert(response.razorpay_signature);
        $.ajax({
          type:"PATCH",
          url:"/orders/<%= @order.id %>",
          dataType:"json",
          data: {
            razorpay_order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
            amount: <%= @order.total_price/100 %>
          },
          success:function(result){
            debugger;
            alert(result);
          }
        });
        window.location = "/orders";
    },
    "prefill": {
        "name": "<%= current_user.name %>",
        "email": "<%= current_user.email %>",
        "contact": "<%= current_user.phone_number %>"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
    rzp1.open();
    e.preventDefault();
}
</script>

app/views/orders/payments.html.erb
<button id="rzp-button1">Pay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "YOUR_KEY_ID", // Enter the Key ID generated from the Dashboard
    "amount": "50000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Acme Corp",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "order_IluGWxBm9U8zJ8", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){
        alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature)
    },
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9999999999"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

app/views/orders/show_order_item.html.erb
<h2>detail of my order</h2>
<%if @order_item.product.image.present?%>
    <%= link_to product_path(@order_item.product_id) do%>
      <%= image_tag @order_item.product.image %></a>
    <%end%>
<% end %>

<h3>price of product = <%= @order_item.total_price %> </h3>
<h3>quantity of prduct = <%= @order_item.product_quantity %> </h3>
<h3>manufacturing date of product = <%= @order_item.product.manufacturing_date %> </h3>
<h3> ordered date = <%= @order_item.created_at%></h3>
<%#= link_to "show products ", product_path(@order_item.product_id)%>
<%if @address.present?%>
   <h3> address of user =<strong><%= @address.flat_no%>, <%= @address.colony%>, <%= @address.landmark%>, <%= @address.city%>, <%= @address.pin_code%></strong></h3>
<%end%>



<% @order_items.each do |c| %>
  <div>
    <%if c.product.image.present?%>
      <%= link_to show_order_item_order_path(c.id) do %>
        <%= image_tag c.product.image, :size => "100x150" %>
      <% end %>
       <%#=link_to image_tag (c.product.image), :size => "100x150"%>
       <%#= link_to "more", show_order_item_order_path(c.id) %>
    <%end%>
  </div>  
<%end%>