config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
    root to: "home#index"



    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do
        devise_for :users, controllers: {
          sessions: 'api/v1/users/sessions',
          registrations: 'api/v1/users/registrations'
        },path: '', path_names: {
          sign_in: 'login',
          sign_out: 'logout',
          registration: 'signup'
        }
        resources :users do 
          put "/otp_varify", to: "users#otp_varify", on: :collection
          put "/otp_varify_email", to: "users#otp_varify_email", on: :collection
        end
      end
    end

    namespace :api, constraints: { format: :json }  do
      namespace :v1, constraints: { format: :json }  do 
        resources :home do 
          get "/add_to_cart", to: "home#add_to_cart"  #post
          post "/like", to: "home#like"
        end
      end
    end

    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do 
        resources :products do 
          resources :comments
          collection do 
            get :options_for_variant
          end
          post "/like", to: "products#like"
        end
        resources :carts do 
          post "/update_cart", to: "carts#update_cart"
          delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
        end
        resources :orders do 
          post "/place_order", to: "orders#place_order", on: :collection
          get "/show_order_item", to: "orders#show_order_item", on: :member
          get "/pay", to: "orders#pay", on: :member
          post "/payments", to: "orders#payments", on: :collection
          patch "/cancel_order", to: "orders#cancel_order", on: :member
        end
        resources :addresses

        resources :variants
      end
    end
    
    get '/member-data', to: 'members#show'

    resources :home do 
      get "/add_to_cart", to: "home#add_to_cart"  #post
      post "/like", to: "home#like"
    end

    resources :carts do 
      post "/update_cart", to: "carts#update_cart"
      delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
    end

    post 'admin/products/change_variant_attribute' 

    resources :products do 
      resources :comments
      collection do 
        get :options_for_variant
      end
      post "/like", to: "products#like"
    end

    resources :variants

    resources :orders do 
      post "/place_order", to: "orders#place_order", on: :collection
      get "/show_order_item", to: "orders#show_order_item", on: :member
      get "/pay", to: "orders#pay", on: :member
      post "/payments", to: "orders#payments", on: :collection
      patch "/cancel_order", to: "orders#cancel_order", on: :member
      
    end

    resources :addresses

    resources :wishlists

end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	validates_uniqueness_of :user_id

    has_many :cart_items, dependent: :destroy
    has_many :products, through: :cart_items
end

app/controllers/api/v1/carts_controller.rb
module Api
	module V1
		class CartsController < ApiController
                before_action :authenticate_user!

			  def index
			  		if current_user.user_type != "merchant"
				        @carts = current_user.cart
				        @cart_item = current_user.cart.cart_items if @carts.present?
				        @addresses = current_user.addresses
				        render json: {cart_item: @cart_item, cart: @carts, meta: {message: 'cart items in cart'}}
				    else
				    	render json: {meta: {message: 'not authorised'}}
			    	end
			  end

			  def destroy_cart_item
			  	if current_user.present?
				    @cart_item = current_user.cart.cart_items.find_by(id: params[:id])
				    if @cart_item.present?
				       @cart_item.destroy
				       render json: {data: @cart_item, meta: {message: 'cart item deleted'}}
				    else
				    	render json: {meta: {message: 'cart item already deleted'}}
				    end
				end
			  end

			  def update_cart
			  	if current_user.present?
				    cart_item = CartItem.find_by(id: params[:cart_id])
				    # byebug
				    pro_price = cart_item.product.price  
				    up_quantity = cart_item.update(product_quantity: params[:product_quantity].to_i, total_price: params[:product_quantity].to_i * pro_price)
				    render json:{data: up_quantity, meta: {message: 'cart item updated'} } 
				end
			  end


			private
			    def cart_item_params
			      # byebug
			      params.require(:cart).permit(:product_id, :cart_id, :total_price, :product_quantity, :destroy)
			    end
		end
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
        @carts = current_user.cart
        @cart_item = current_user.cart.cart_items if @carts.present?
        @addresses = current_user.addresses
  end

  def destroy_cart_item
    @cart_item = current_user.cart.cart_items.find_by(id: params[:id])
    if @cart_item.present?
       @cart_item.destroy
    end
    redirect_to carts_path
  end

  def update_cart
    cart_item = CartItem.find_by(id: params[:cart_id])
    pro_price = cart_item.product.price  
    up_quantity = cart_item.update(product_quantity: params[:product_quantity].to_i, total_price: params[:product_quantity].to_i * pro_price)
    redirect_to carts_path
  end


private
    def cart_item_params
      # byebug
      params.require(:cart).permit(:product_id, :cart_id, :total_price, :product_quantity, :destroy)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<style>
    .pp {
    color: red;
    }
</style>


<center>
    <h3 class="pp"><%= flash[:error]%> </h3>
    <h2>User Cart</h2>

<% if @carts.present? %>
<div class="row">
   <% if @cart_item.present? %>
      <% @cart_item.each do |c| %>  
         <div class="column">
 	     	     <%if c.product.image.present?%>
                 <%= image_tag c.product.image, :size => "100x150" %>
              <%end%>
         </div>
         
         <div class="column">
            <h4>price = <%= c.total_price%></h4>
            <h4> product id = <%= c.product_id%><br></h4>
            <h4>name = <%= c.product.name%></h4>
             <%#= c.product_quantity%>

                   <%= form_with url: cart_update_cart_path(cart_id: c), method: "post" do |form| %>
                        <h4>
                        quantity = <%= form.number_field :product_quantity, :value => c.product_quantity %>
                        <br></h4>
                      <%= form.submit %>
                   <% end %>
                   <%#byebug%>
           <h4><%= link_to "Destroy", destroy_cart_item_cart_path(c.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></h4>
         </div><br>

      <%end %>     
   <%end %>
</div><br><br>
<%#byebug%>
<% if @cart_item.present?%>
     <h3><strong>total price = </strong><%= @carts.total_price %></h3>
     <h3><strong>total quantity = </strong> <%= @carts.total_quantity%></h3>
 <% end %>

<%end %>
<br>
<br>
<br>
</center>

<% if @cart_item.present?%>
    <%= form_with url: place_order_orders_path, method: "post" do |form| %>
        <% @addresses.each do |address| %>
            <h4>
                <%= form.radio_button :address_id, address.id %> 
                <label><%= address.flat_no %>, <%= address.colony %>,  <%= address.landmark %>, <%= address.city %>, <%= address.pin_code %></label>
            </h4>
        <% end %>
        <%= form.submit  "place order"%>

    <% end %>
<%end%>


<h3 align="right"><div style="text-indent: 1300px;"><%= link_to 'new address for user', new_address_path%></div></h3>
<h3 align="right"><%#= link_to 'place order', place_order_orders_path%></h3>
<h3 align="right"><%= link_to 'back', home_index_path %></h3> 























































<!-- 
  twillo
  Sup@12345678riya -->