config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
    root to: "home#index"



    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do
        devise_for :users, controllers: {
          sessions: 'api/v1/users/sessions',
          registrations: 'api/v1/users/registrations'
        },path: '', path_names: {
          sign_in: 'login',
          sign_out: 'logout',
          registration: 'signup'
        }
        resources :users do 
          put "/otp_varify", to: "users#otp_varify", on: :collection
          put "/otp_varify_email", to: "users#otp_varify_email", on: :collection
        end
      end
    end

    namespace :api, constraints: { format: :json }  do
      namespace :v1, constraints: { format: :json }  do 
        resources :home do 
          get "/add_to_cart", to: "home#add_to_cart"  #post
          post "/like", to: "home#like"
        end
      end
    end

    namespace :api, constraints: { format: :json } do
      namespace :v1, constraints: { format: :json } do 
        resources :products do 
          resources :comments
          collection do 
            get :options_for_variant
          end
          post "/like", to: "products#like"
        end
        resources :carts do 
          post "/update_cart", to: "carts#update_cart"
          delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
        end
        resources :orders do 
          post "/place_order", to: "orders#place_order", on: :collection
          get "/show_order_item", to: "orders#show_order_item", on: :member
          get "/pay", to: "orders#pay", on: :member
          post "/payments", to: "orders#payments", on: :collection
          patch "/cancel_order", to: "orders#cancel_order", on: :member
        end
        resources :addresses

        resources :variants
      end
    end
    
    get '/member-data', to: 'members#show'

    resources :home do 
      get "/add_to_cart", to: "home#add_to_cart"  #post
      post "/like", to: "home#like"
    end

    resources :carts do 
      post "/update_cart", to: "carts#update_cart"
      delete "/destroy_cart_item", to: "carts#destroy_cart_item", on: :member
    end

    post 'admin/products/change_variant_attribute' 

    resources :products do 
      resources :comments
      collection do 
        get :options_for_variant
      end
      post "/like", to: "products#like"
    end

    resources :variants

    resources :orders do 
      post "/place_order", to: "orders#place_order", on: :collection
      get "/show_order_item", to: "orders#show_order_item", on: :member
      get "/pay", to: "orders#pay", on: :member
      post "/payments", to: "orders#payments", on: :collection
      patch "/cancel_order", to: "orders#cancel_order", on: :member
      
    end

    resources :addresses

    resources :wishlists

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>My Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
     margin: 4px;
    }
        
      .mess {
          color: green;
          }

      .fgh {
        list-style-type: inline;
        margin: 0;
        padding: 0;
        width: 100%;
        //background-color: #f1f1f1;
        background-color: #c1c4dc;
        //position: fixed;
        height: 10%;
        overflow: auto;

      }

      .nav {
        display: block;
        color: #000;
        padding: 8px 16px;
        text-decoration: none;
        display: inline;
      }

      .active {
        background-color: #04AA6D;
        color: white;
      }

      #menu:hover:not(.active) {
        background-color: #555;
        color: white;
        
      }

      #menu:link, #menu:visited{
        color: #081520;
        text-decoration: none;
        padding:20px ;
        }

    </style>
  </head>

  <body>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>

      <p class="navbar-text float-right">
        <% if user_signed_in? %>
          <div class="fgh">
              <% if current_user.user_type == "merchant"%>
                   <h3 align="left", padding="5px"> 
                     <a class="nav" class="active" id="menu" href="<%= home_index_path %>"><%= "home"%></a>   
                     <a class="nav" class="active" id="menu" href="<%= new_product_path %>"><%= "new product"%></a> 
                     <a class="nav" class="active" id="menu" href="<%= new_variant_path %>"><%= "new variant"%></a> 
                  </h3>

              <%else%>
                  <h3 align="left", padding="5px">   
                     <a class="nav" class="active" id="menu" href="<%= home_index_path %>"><%= "home"%></a> 
                     <a class="nav" class="active" id="menu" href="<%= carts_path %>"><%= "show cart"%></a>  
                     <a class="nav" class="active" id="menu" href="<%= orders_path %>"><%= "my orders"%></a> 
                     <%#byebug%>
                     <a class="nav" class="active" id="menu" href="<%= wishlists_path %>"><%= "my wishlist"%></a> 
                  </h3> 
              <% end%>
          </div>
        <%end%>
         
      </p>




      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>

  </body>
</html>